[fix] build on Linux >= 5.1
Build failed with this error:
udmabuf.c:527:16: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
  527 |     .fault   = udmabuf_device_vma_fault,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~

Starting from Linux 5.1 'vm_fault_t' switches from int to unsigned int.

vm_fault_t was defined from Linux 4.17, so this commit adds its
definition for Linux < 4.17, and it uses vm_fault_t return value for
.fault callback.